name: Terraform CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
